package mapping;
// Generated 25-ene-2021 20:29:02 by Hibernate Tools 4.3.1



/**
 * Disponible generated by hbm2java
 */
public class Disponible  implements java.io.Serializable {


     private Integer id;
     private int pid;
     private int sid;
     private int tid;
     private int fila;
     private String letra;
     private String butacas;
     private int estado;
     private int pos;

    public Disponible() {
    }

    public Disponible(int pid, int sid, int tid, int fila, String letra, String butacas, int estado, int pos) {
       this.pid = pid;
       this.sid = sid;
       this.tid = tid;
       this.fila = fila;
       this.letra = letra;
       this.butacas = butacas;
       this.estado = estado;
       this.pos = pos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getPid() {
        return this.pid;
    }
    
    public void setPid(int pid) {
        this.pid = pid;
    }
    public int getSid() {
        return this.sid;
    }
    
    public void setSid(int sid) {
        this.sid = sid;
    }
    public int getTid() {
        return this.tid;
    }
    
    public void setTid(int tid) {
        this.tid = tid;
    }
    public int getFila() {
        return this.fila;
    }
    
    public void setFila(int fila) {
        this.fila = fila;
    }
    public String getLetra() {
        return this.letra;
    }
    
    public void setLetra(String letra) {
        this.letra = letra;
    }
    public String getButacas() {
        return this.butacas;
    }
    
    public void setButacas(String butacas) {
        this.butacas = butacas;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public int getPos() {
        return this.pos;
    }
    
    public void setPos(int pos) {
        this.pos = pos;
    }




}


