package mapping;
// Generated 25-ene-2021 20:29:02 by Hibernate Tools 4.3.1



/**
 * PaseSala generated by hbm2java
 */
public class PaseSala  implements java.io.Serializable {


     private Integer id;
     private int sid;
     private int tid;

    public PaseSala() {
    }

    public PaseSala(int sid, int tid) {
       this.sid = sid;
       this.tid = tid;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getSid() {
        return this.sid;
    }
    
    public void setSid(int sid) {
        this.sid = sid;
    }
    public int getTid() {
        return this.tid;
    }
    
    public void setTid(int tid) {
        this.tid = tid;
    }




}


