package mapping;
// Generated 25-ene-2021 20:29:02 by Hibernate Tools 4.3.1



/**
 * Pases generated by hbm2java
 */
public class Pases  implements java.io.Serializable {


     private Integer tid;
     private String hora;

    public Pases() {
    }

    public Pases(String hora) {
       this.hora = hora;
    }
   
    public Integer getTid() {
        return this.tid;
    }
    
    public void setTid(Integer tid) {
        this.tid = tid;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }




}


