package mapping;
// Generated 25-ene-2021 20:29:02 by Hibernate Tools 4.3.1



/**
 * Peliculas generated by hbm2java
 */
public class Peliculas  implements java.io.Serializable {


     private Integer pid;
     private String titulo;
     private String director;
     private String nacionalidad;
     private String genero;
     private String clasificacion;
     private String descr;
     private double duracion;
     private String actores;
     private String linkExterior;
     private String linkImagen;
     private int estado;

    public Peliculas() {
    }

    public Peliculas(String titulo, String director, String nacionalidad, String genero, String clasificacion, String descr, double duracion, String actores, String linkExterior, String linkImagen, int estado) {
       this.titulo = titulo;
       this.director = director;
       this.nacionalidad = nacionalidad;
       this.genero = genero;
       this.clasificacion = clasificacion;
       this.descr = descr;
       this.duracion = duracion;
       this.actores = actores;
       this.linkExterior = linkExterior;
       this.linkImagen = linkImagen;
       this.estado = estado;
    }
   
    public Integer getPid() {
        return this.pid;
    }
    
    public void setPid(Integer pid) {
        this.pid = pid;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDirector() {
        return this.director;
    }
    
    public void setDirector(String director) {
        this.director = director;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public String getClasificacion() {
        return this.clasificacion;
    }
    
    public void setClasificacion(String clasificacion) {
        this.clasificacion = clasificacion;
    }
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }
    public double getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(double duracion) {
        this.duracion = duracion;
    }
    public String getActores() {
        return this.actores;
    }
    
    public void setActores(String actores) {
        this.actores = actores;
    }
    public String getLinkExterior() {
        return this.linkExterior;
    }
    
    public void setLinkExterior(String linkExterior) {
        this.linkExterior = linkExterior;
    }
    public String getLinkImagen() {
        return this.linkImagen;
    }
    
    public void setLinkImagen(String linkImagen) {
        this.linkImagen = linkImagen;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }

    @Override
    public String toString() {
        return "Peliculas{" + "pid=" + pid + ", titulo=" + titulo + ", director=" + director + ", nacionalidad=" + nacionalidad + ", genero=" + genero + ", clasificacion=" + clasificacion + ", descr=" + descr + ", duracion=" + duracion + ", actores=" + actores + ", linkExterior=" + linkExterior + ", linkImagen=" + linkImagen + ", estado=" + estado + '}';
    }


    

}


