package mapping;
// Generated 25-ene-2021 20:29:02 by Hibernate Tools 4.3.1



/**
 * PeliculaSala generated by hbm2java
 */
public class PeliculaSala  implements java.io.Serializable {


     private Integer id;
     private int sid;
     private int pid;
     private int estado;

    public PeliculaSala() {
    }

    public PeliculaSala(int sid, int pid, int estado) {
       this.sid = sid;
       this.pid = pid;
       this.estado = estado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getSid() {
        return this.sid;
    }
    
    public void setSid(int sid) {
        this.sid = sid;
    }
    public int getPid() {
        return this.pid;
    }
    
    public void setPid(int pid) {
        this.pid = pid;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }




}


