package mapping;
// Generated 25-ene-2021 20:29:02 by Hibernate Tools 4.3.1



/**
 * Salas generated by hbm2java
 */
public class Salas  implements java.io.Serializable {


     private Integer sid;
     private String descr;

    public Salas() {
    }

    public Salas(String descr) {
       this.descr = descr;
    }
   
    public Integer getSid() {
        return this.sid;
    }
    
    public void setSid(Integer sid) {
        this.sid = sid;
    }
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }




}


